### ISSUE TITLE
Make easier to fork and add contribution guide

### ISSUE THREAD

**Issue by mat-1** [mat-1/forum-sweats#1]
Setting bot options like the token, prefix, main server id, etc, should be easier, and there should be a file that documents what values should be set and where

**Comment by LiteLT** [comment]
Wouldn't it be more appropriate to store the setup guide in `READMD.md`, its own dedicated `SETUP.md` file, or a script to generate it? The `CONTRIBUTING.md` file is usually for developers contributing to the project through issues and pull requests.
