### ISSUE TITLE
Replace auto updating giveaway timestamp with discord timestamps 

### ISSUE THREAD

**Issue by tomekczpog** [mat-1/forum-sweats#113]
Discord has added a new feature that allows you to add timestamps to messages
for example <t:1:R> (you can even send it in any chat without a bot and it will work)
<t:(time):(Style)>
Here are the styles
![image](https://user-images.githubusercontent.com/74684114/129923775-7bf3b00e-4f28-4533-8a7f-45039a82950b.png)
I think you should replace the giveaway auto updating time with this

**Comment by mat-1** [comment]
Yeah I considered doing that, but it works fine as it is right now and the Discord timestamp things don't auto update without switching channels.
