### ISSUE TITLE
Bobux text adventures

### ISSUE THREAD

**Issue by fiftyplus50** [mat-1/forum-sweats#22]
Text adventures that people can go on for bobux prizes and such. I can write the stories and stuff while you code. Also one problem I foresee with this is people memorizing all possible scenarios.

Here are some examples of possible quests:
You go kakistan to retrieve a bobux idol. You must venture through the forest and a temple full of traps to get it. You can trade in the bobux idol for 100 bobux.

You find the site of the bobux grail after passing 3 tests. You realize that it’s missing. Investigate the room to find when it was stolen and where. Go and confront the thief and stone them.

Sorry for bad formatting, I’m on a phone. Also sorry for basically ripping Indiana Jones 1 and 3 for these lmao

**Comment by mat-1** [comment]
Add more details to the example pls
