### ISSUE TITLE
Add !editmute

### ISSUE THREAD

**Issue by antisynth** [mat-1/forum-sweats#69]
## Command syntax
!editmute user, new length, reason

**Reason will be optional.**

## Errors
If there isn't a specified user, send a message saying that the message author needs to specify a user to change the mute length of and return.

If there isn't a length, send a message saying that the message author needs to specify a new length and return.

If the user they try to change the mute length of isn't muted, send a message saying that the user the message author entered isn't muted and return.
## Command
When the command is executed successfully the bot will DM the user saying "Your mute has been extended to {length}" if there isn't a reason, and "Your mute has been extended to {length} for {reason}" if there is one. 
Then, the bot will change the length of the user's mute to whatever length the message author inputs and will **not** add a new infraction.
## Why tho?
This could be useful in case a staff member enters a length that is far too short or too long, when muting a user that is breaking the rules. Instead of having to change the mute length, and clear the user's recent infraction, they can just use this command to easily change the mute length and not have to deal with clearing a new infraction.
## Example
![image](https://user-images.githubusercontent.com/73140189/101266695-8ed00780-370e-11eb-9307-083876110c31.png)
![image](https://user-images.githubusercontent.com/73140189/101266667-47497b80-370e-11eb-9a61-1656f8c0ec67.png)
![image](https://user-images.githubusercontent.com/73140189/101266677-67793a80-370e-11eb-8feb-20122bf25d97.png)
![image](https://user-images.githubusercontent.com/73140189/101266697-92638e80-370e-11eb-853d-6b4d4fdf1da5.png)

**Comment by antisynth** [comment]
I don't know how to add the "enhancement" and "new command" thingy but that's what this is

**Comment by mat-1** [comment]
(Resolved by #70)
