### ISSUE TITLE
Pets - Gladiator Pet

### ISSUE THREAD

**Issue by joeythemanford** [mat-1/forum-sweats#85]
**Gladiator Pet** 

**Win streak** 
Winning duels in a row (in general) grants you more and more bobux, winning one duel grants you some, but when you reach 10 in a row you get upwards to 30. If you duel the same person multiple times in a row, you won’t get bobux for those subsequent wins. If you are caught using alts to abuse this, you will be muted.

1 Win - 0 Bobux
2 Wins - 0 Bobux
3 Wins - 5 Bobux
4 Wins - 10 Bobux
5 Wins - 15 Bobux
6 Wins - 15 Bobux
7 Wins - 20 Bobux
8 Wins - 20 Bobux
9 Wins - 25 Bobux
10 Wins - 30 Bobux
Anything beyond - 30 bobux

**Harder Blows**
If you win a duel in general, your opponent gets muted for 90 minutes instead of an hour.

**Gladiator**
Has a chance to rig duels, making you win it, an ability that levels up every 10 duels won, it caps at lvl 5. Here are the %s as it levels up:

*Level 1:* 1% to rig
*Level 2:* 2% to rig
*Level 3:* 3% to rig
*Level 4:* 4% to rig
*Level 5:* 5% to rig

—————————————

To get this pet you need to **win 15 duels** in general against different people. After you win those duels, you can buy this pet from **the shop for 1800 bobux**.

**Comment by mat-1** [comment]
> Winning duels in a row (in general) grants you more and more bobux, winning one duel grants you some, but when you reach 10 in a row you get upwards to 30 per.

There should be no rewards for 1-2 wins, and all the duels should have to be against different people, so you can't just keep dueling the same people that are really bad at duels

**Comment by joeythemanford** [comment]
> > Winning duels in a row (in general) grants you more and more bobux, winning one duel grants you some, but when you reach 10 in a row you get upwards to 30 per.
> 
> There should be no rewards for 1-2 wins, and all the duels should have to be against different people, so you can't just keep dueling the same people that are really bad at duels. Also the requirements should be easier so you don't need to find 30 people to duel with

Fixed
